version: '3'

tasks:
  all:
    cmds:
      - task: cleanup
      - task: build
      - task: package
    silent: true

  build:
    cmds:
      - rm -rf build
      - mkdir -p build
      - mkdir -p build/lib
      - docker buildx build --platform=linux/arm64 -t logjack-arm64 -f Dockerfile .
    silent: true

  package:
    cmds:
      - docker create --name extract logjack-arm64 || true
      - docker cp extract:/build/logjack build/logjack
      - docker cp extract:/usr/lib/aarch64-linux-gnu/libSDL2_gfx-1.0.so.0.0.2 build/lib/libSDL2_gfx-1.0.so.0
      - rm -rf "build/Log Jack.pak" || true
      - mkdir -p "build/Log Jack.pak"
      - mkdir -p "build/Log Jack.pak/resources/lib"
      - cp build/logjack launch.sh README.md LICENSE pak.json logjack.ini "build/Log Jack.pak"
      - cp -R build/lib "build/Log Jack.pak/resources"
    silent: true

  cleanup:
    cmds:
      - docker rm extract || true
    silent: true

  adb:
    cmds:
      - adb shell rm -rf "/mnt/SDCARD/Tools/tg5040/Log Jack.pak" || true
      - adb push "build/Log Jack.pak" "/mnt/SDCARD/Tools/tg5040"
    silent: true

  clean:
    cmds:
      - rm -rf build
    silent: true
